name = "healthchain/contracts"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for HealthChain"

[repository]
user = "healthchain"
project = "contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"
